package com.careeros.placement.service;

import com.careeros.placement.dto.AptitudeTestDto;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

/**
 * Curated, hand-verified aptitude question bank.
 *
 * Every question, answer key, option set and explanation below was authored and
 * verified manually. The LLM path frequently returned wrong answers, keys and
 * explanations, so aptitude now uses this deterministic bank so that generated
 * assessments are accurate and unambiguous.
 *
 * Helper signature is intentionally simple (no extra fixed args before the
 * options) so a question's 4 options always map 1:1 and the correctAnswerIndex
 * always points at the right option.
 */
@Component
public class AptitudeQuestionBank {

    private static final String DEFAULT_COMPANIES = "TCS, Infosys, Wipro, Accenture";
    private static final String DEFAULT_TIME = "60 sec";

    public List<AptitudeTestDto.Question> questionsFor(String category) {
        return BANK.getOrDefault(category == null ? "QUANTITATIVE" : category.toUpperCase(), QUANTITATIVE);
    }

    public int sizeFor(String category) {
        return questionsFor(category).size();
    }

    private static AptitudeTestDto.Question q(String id, String text, int correct, String difficulty, String topic,
                                              String explanation, String... options) {
        return new AptitudeTestDto.Question(id, text, List.of(options), correct, explanation, null, difficulty,
                DEFAULT_COMPANIES, topic, null, null, DEFAULT_TIME, 1);
    }

    // ---------------------------------------------------------------- QUANTITATIVE
    private static final List<AptitudeTestDto.Question> QUANTITATIVE = List.of(
            q("q1",
              "A train 120 m long crosses a pole in 12 seconds. What is its speed in km/h?",
              1, "MEDIUM", "Time, Speed and Distance",
              "Speed = Distance / Time = 120 m / 12 s = 10 m/s. Convert m/s to km/h by multiplying by 18/5: 10 × 18/5 = 36 km/h.",
              "30", "36", "48", "40"),
            q("q2",
              "What is the simple interest on Rs 5000 at 8% per annum for 3 years?",
              1, "EASY", "Simple Interest",
              "SI = (P × R × T) / 100 = (5000 × 8 × 3) / 100 = 120000 / 100 = Rs 1200.",
              "Rs 1000", "Rs 1200", "Rs 1400", "Rs 1600"),
            q("q3",
              "If 15 men can complete a job in 24 days, in how many days can 20 men complete the same job?",
              3, "MEDIUM", "Work and Time",
              "Total work = 15 × 24 = 360 man-days. With 20 men, days = 360 / 20 = 18 days.",
              "20", "16", "22", "18"),
            q("q4",
              "The average of five consecutive even numbers is 18. What is the largest of them?",
              2, "MEDIUM", "Averages",
              "The middle (3rd) of five consecutive evens equals the average, so middle = 18. The largest is two steps ahead: 18 + 4 = 22.",
              "20", "24", "22", "18"),
            q("q5",
              "A shopkeeper sells an article for Rs 720 at a profit of 20%. What was its cost price?",
              1, "MEDIUM", "Profit and Loss",
              "CP = SP / (1 + profit%) = 720 / 1.20 = Rs 600.",
              "Rs 650", "Rs 600", "Rs 680", "Rs 720"),
            q("q6",
              "What is 30% of 250 added to 25% of 200?",
              0, "EASY", "Percentages",
              "30% of 250 = 75 and 25% of 200 = 50. Total = 75 + 50 = 125.",
              "125", "130", "120", "135"),
            q("q7",
              "A number, when increased by 25%, becomes 625. What is the number?",
              3, "MEDIUM", "Percentages",
              "x × 1.25 = 625, so x = 625 / 1.25 = 500.",
              "480", "450", "420", "500"),
            q("q8",
              "Two numbers are in the ratio 3 : 4 and their sum is 84. What is the larger number?",
              1, "EASY", "Ratio and Proportion",
              "Let the numbers be 3x and 4x. 3x + 4x = 7x = 84, so x = 12. Larger = 4 × 12 = 48.",
              "36", "48", "42", "54"),
            q("q9",
              "If x% of 400 equals 60, what is x?",
              0, "EASY", "Percentages",
              "(x/100) × 400 = 60 → 4x = 60 → x = 15.",
              "15", "12", "20", "18"),
            q("q10",
              "A father is three times as old as his son. The difference in their ages is 24 years. How old is the son?",
              2, "MEDIUM", "Ages",
              "Let son = s, father = 3s. 3s − s = 2s = 24 → s = 12 years.",
              "16", "8", "12", "10"),
            q("q11",
              "A boat covers 40 km downstream in 4 hours. If the speed of the stream is 2 km/h, what is the speed of the boat in still water?",
              0, "MEDIUM", "Boats and Streams",
              "Downstream speed = 40 / 4 = 10 km/h = Boat + Stream. Boat = 10 − 2 = 8 km/h.",
              "8 km/h", "10 km/h", "6 km/h", "12 km/h"),
            q("q12",
              "The area of a rectangle is 240 sq m and its length is 20 m. What is its perimeter?",
              3, "MEDIUM", "Mensuration",
              "Width = 240 / 20 = 12 m. Perimeter = 2(l + b) = 2(20 + 12) = 2 × 32 = 64 m.",
              "56", "32", "48", "64"),
            q("q13",
              "What is the compound interest on Rs 10,000 at 10% per annum for 2 years?",
              3, "MEDIUM", "Compound Interest",
              "Amount = 10000 × (1.10)² = 10000 × 1.21 = 12100. CI = 12100 − 10000 = Rs 2100.",
              "2000", "2200", "1900", "2100"),
            q("q14",
              "What is the LCM of 12 and 18?",
              0, "EASY", "HCF & LCM",
              "12 = 2² × 3 and 18 = 2 × 3². LCM = 2² × 3² = 4 × 9 = 36.",
              "36", "24", "72", "18"),
            q("q15",
              "A man walks at 5 km/h and covers a distance in 3 hours. How long will he take to cover the same distance at 6 km/h?",
              2, "MEDIUM", "Time, Speed and Distance",
              "Distance = 5 × 3 = 15 km. Time = 15 / 6 = 2.5 hours.",
              "2 h", "2.4 h", "2.5 h", "3 h"),
            q("q16",
              "If 5 pens cost Rs 75, what is the cost of 12 pens?",
              1, "EASY", "Unitary Method",
              "Cost per pen = 75 / 5 = Rs 15. Cost of 12 pens = 12 × 15 = Rs 180.",
              "Rs 150", "Rs 180", "Rs 165", "Rs 200"));

    // ---------------------------------------------------------------- LOGICAL
    private static final List<AptitudeTestDto.Question> LOGICAL = List.of(
            q("L1",
              "In a certain code, CAT is written as DBU. How is DOG written in that code?",
              0, "EASY", "Coding-Decoding",
              "Each letter is shifted one place forward. D→E, O→P, G→H = EPH.",
              "EPH", "FQI", "EPG", "DPI"),
            q("L2",
              "Find the odd one out: 2, 6, 12, 20, 30, 42, 56, 72, 90, 111",
              1, "MEDIUM", "Number Series",
              "The pattern is n(n+1): 1×2=2, 2×3=6 ... 10×11=110. The 10th term should be 110, not 111.",
              "90", "111", "72", "56"),
            q("L3",
              "3, 9, 27, 81, ? Find the next number.",
              3, "EASY", "Number Series",
              "Each term is multiplied by 3: 3, 9, 27, 81, 243.",
              "162", "180", "216", "243"),
            q("L4",
              "Statements: All students are scholars. Some scholars are athletes. Which conclusion definitely follows?\nI. Some students are athletes.\nII. Some athletes are scholars.",
              0, "MEDIUM", "Syllogism",
              "From 'Some scholars are athletes' we can directly say some athletes are scholars (II). I does not follow because students are only a subset of scholars.",
              "Only II follows", "Only I follows", "Both I and II follow", "Neither follows"),
            q("L5",
              "In a row of people, A is 7th from the left and 8th from the right. How many people are in the row?",
              1, "EASY", "Ranking",
              "Total = position from left + position from right − 1 = 7 + 8 − 1 = 14.",
              "15", "14", "13", "16"),
            q("L6",
              "If tomorrow is Thursday, what day was the day before yesterday?",
              0, "EASY", "Calendar / Days",
              "Tomorrow Thursday → today Wednesday → yesterday Tuesday → the day before yesterday Monday.",
              "Monday", "Tuesday", "Sunday", "Friday"),
            q("L7",
              "P, Q, R and S are siblings. S is the oldest. P is older than Q, and Q is older than R. Who is the youngest?",
              0, "MEDIUM", "Ordering",
              "Ordering S > P > Q > R, so R is the youngest.",
              "R", "Q", "P", "Cannot be determined"),
            q("L8",
              "What is the angle between the hour and minute hands of a clock at 3:15?",
              0, "HARD", "Clock",
              "Minute hand = 15 × 6 = 90°. Hour hand = 3 × 30 + 15 × 0.5 = 97.5°. Difference = 97.5 − 90 = 7.5°.",
              "7.5°", "45°", "15°", "0°"),
            q("L9",
              "If '+' means '×', '−' means '÷', '×' means '−' and '÷' means '+', then evaluate: 8 ÷ 4 − 2 × 1 + 3",
              1, "HARD", "Mathematical Operations",
              "Replace operators: 8 + 4 ÷ 2 − 1 × 3. By precedence: 4 ÷ 2 = 2 → 8 + 2 − 3 = 7.",
              "6", "7", "8", "9"),
            q("L10",
              "5, 10, 17, 26, 37, ? Find the next number.",
              0, "MEDIUM", "Number Series",
              "Differences are consecutive odd numbers: +5, +7, +9, +11, +13. Next = 37 + 13 = 50.",
              "50", "47", "49", "48"),
            q("L11",
              "P is the brother of Q, and Q is the mother of R. What is P to R?",
              0, "MEDIUM", "Blood Relations",
              "P (male) is Q's brother and Q is R's mother, so P is R's maternal uncle.",
              "Uncle", "Father", "Grandfather", "Nephew"),
            q("L12",
              "Find the odd one out: 11, 13, 17, 19, 23, 25, 29",
              1, "EASY", "Prime / Composite",
              "Every number is prime except 25, which is 5 × 5.",
              "23", "25", "19", "17"));

    // ---------------------------------------------------------------- VERBAL
    private static final List<AptitudeTestDto.Question> VERBAL = List.of(
            q("V1",
              "Choose the word closest in meaning to ABUNDANT.",
              0, "EASY", "Synonyms",
              "Abundant means existing in large quantities, i.e. plentiful.",
              "Plentiful", "Scarce", "Meager", "Sparse"),
            q("V2",
              "Choose the antonym of MELANCHOLY.",
              0, "EASY", "Antonyms",
              "Melancholy means sadness; jovial (cheerful) is its opposite.",
              "Jovial", "Somber", "Gloomy", "Dismal"),
            q("V3",
              "Select the correct word: The committee was divided and could not arrive at a ___.",
              0, "MEDIUM", "Sentence Completion",
              "Consensus = general agreement, which fits the context.",
              "consensus", "collision", "confluence", "consort"),
            q("V4",
              "Choose the correctly spelled word.",
              0, "MEDIUM", "Spelling",
              "The standard spelling is 'accommodate' (double c, double m).",
              "Accommodate", "Accomodate", "Acommodate", "Accommodte"),
            q("V5",
              "Choose the synonym of DILIGENT.",
              0, "EASY", "Synonyms",
              "Diligent = hard-working, i.e. industrious.",
              "Industrious", "Lazy", "Indolent", "Idle"),
            q("V6",
              "Choose the antonym of TRANSPARENT.",
              0, "EASY", "Antonyms",
              "Transparent means see-through; opaque is its opposite.",
              "Opaque", "Clear", "Lucid", "Translucent"),
            q("V7",
              "Choose the correct verb: One of the students ___ late today.",
              0, "MEDIUM", "Grammar",
              "The subject 'One' is singular, so the verb is 'was'.",
              "was", "were", "are", "be"),
            q("V8",
              "Which of the following is a noun?",
              0, "EASY", "Parts of Speech",
              "Happiness is a noun; the others are adjective/adverb forms.",
              "Happiness", "Happy", "Happily", "Happier"),
            q("V9",
              "Choose the correctly punctuated sentence.",
              0, "MEDIUM", "Punctuation",
              "Only option A uses the correct apostrophe (contraction of 'It is') and a terminal period.",
              "It's a beautiful day.", "Its a beautiful day", "Its' a beautiful day.", "It's a beautiful day, "),
            q("V10",
              "Choose the closest meaning of EPHEMERAL.",
              0, "HARD", "Synonyms",
              "Ephemeral means lasting for a very short time, i.e. fleeting.",
              "Fleeting", "Permanent", "Enduring", "Eternal"));

    // ---------------------------------------------------------------- PUZZLE
    private static final List<AptitudeTestDto.Question> PUZZLE = List.of(
            q("P1",
              "If you have 3 apples and give away all but 2, how many apples do you have left?",
              0, "EASY", "Word Trick",
              "'All but 2' means you keep exactly 2 apples.",
              "2", "0", "1", "3"),
            q("P2",
              "A man has 4 children. Each child has exactly one sister. How many children does the man have altogether?",
              0, "EASY", "Family Puzzle",
              "All 4 children share the same sister, so there are 4 sons plus 1 daughter = 5 children.",
              "5", "4", "8", "3"),
            q("P3",
              "1, 4, 9, 16, 25, ? Find the next number.",
              0, "EASY", "Number Pattern",
              "These are squares 1², 2², 3², 4², 5², so next is 6² = 36.",
              "36", "35", "34", "30"),
            q("P4",
              "A bookseller has 7 books and sells 3 of them. How many books does he have now?",
              0, "EASY", "Simple Arithmetic",
              "7 − 3 = 4 books remain.",
              "4", "3", "7", "10"),
            q("P5",
              "If one-and-a-half hens lay one-and-a-half eggs in one-and-a-half days, how many eggs will 3 hens lay in 3 days?",
              0, "HARD", "Work Rate",
              "Rate per hen per day = 1.5 / (1.5 × 1.5) = 2/3 egg. For 3 hens × 3 days = 3 × 3 × (2/3) = 6 eggs.",
              "6", "4", "3", "9"),
            q("P6",
              "I am a 3-digit number. My tens digit is 3 less than my hundreds digit, and my ones digit is 2 more than my tens digit. My hundreds digit is 7. What am I?",
              0, "MEDIUM", "Digit Puzzle",
              "Hundreds = 7; tens = 7 − 3 = 4; ones = 4 + 2 = 6; number = 746.",
              "746", "764", "734", "756"),
            q("P7",
              "In a group of 30 people, 18 like tea, 15 like coffee, and 8 like both. How many like neither?",
              0, "MEDIUM", "Set Theory",
              "Union = 18 + 15 − 8 = 25. Neither = 30 − 25 = 5.",
              "5", "4", "6", "7"),
            q("P8",
              "A frog climbing out of a 20 m well goes up 3 m and slips back 1 m each turn. How many turns to reach the top?",
              0, "HARD", "Net Distance",
              "Net gain per turn is 2 m. After 9 turns the frog is at 18 m; the 10th climb reaches 18 + 3 = 21 m ≥ 20 m, so it tops out on the 10th turn.",
              "10", "9", "8", "11"),
            q("P9",
              "Two clocks set correctly at noon. One gains 2 minutes per hour and the other loses 1 minute per hour. After 3 hours, what is the difference between their readings?",
              0, "MEDIUM", "Clock Gaining / Losing",
              "Gain = +2 × 3 = +6; loss = −1 × 3 = −3. Difference = 6 + 3 = 9 minutes.",
              "9", "6", "3", "12"),
            q("P10",
              "How many squares are there in a 3 × 3 grid of small squares?",
              0, "MEDIUM", "Counting Figures",
              "1×1 = 9, 2×2 = 4, 3×3 = 1. Total = 9 + 4 + 1 = 14.",
              "14", "9", "12", "13"));

    // ---------------------------------------------------------------- DI
    private static final List<AptitudeTestDto.Question> DI = List.of(
            q("D1",
              "A bar chart shows yearly sales: 2020 = 50, 2021 = 60, 2022 = 75, 2023 = 90 (in thousands). What is the increase from 2021 to 2023?",
              3, "EASY", "Bar Chart",
              "Increase = 90 − 60 = 30 thousand.",
              "25,000", "15,000", "40,000", "30,000"),
            q("D2",
              "Out of 600 students, 240 study Engineering. What percentage is that?",
              0, "EASY", "Percentages of Total",
              "240 / 600 × 100 = 40%.",
              "40%", "30%", "25%", "35%"),
            q("D3",
              "A pie chart of 360° shows Services = 150°. What percentage of the total is Services?",
              0, "MEDIUM", "Pie Chart",
              "150 / 360 × 100 = 41.7%.",
              "41.7%", "35%", "40%", "45%"),
            q("D4",
              "A table shows monthly production: Jan = 120, Feb = 140, Mar = 130, Apr = 160 (in tons). What is the average monthly production?",
              0, "MEDIUM", "Table / Averages",
              "Total = 120 + 140 + 130 + 160 = 550. Average = 550 / 4 = 137.5 tons.",
              "137.5", "135", "140", "132.5"),
            q("D5",
              "A school has 800 students and 60% are girls. How many girls are there?",
              0, "EASY", "Percentages",
              "60% of 800 = 0.60 × 800 = 480.",
              "480", "320", "400", "450"),
            q("D6",
              "A line graph shows population: 2000 = 200, 2005 = 250, 2010 = 300 (in thousands). What is the percentage increase from 2000 to 2010?",
              0, "MEDIUM", "Line Graph",
              "Increase = 100; percent = 100 / 200 × 100 = 50%.",
              "50%", "40%", "60%", "45%"),
            q("D7",
              "A company's 2023 revenue is Rs 6,00,000 and profit is 25% of revenue. What is the profit?",
              0, "EASY", "Percentages of Revenue",
              "Profit = 25% of 600,000 = 0.25 × 600000 = Rs 1,50,000.",
              "Rs 150000", "Rs 125000", "Rs 175000", "Rs 200000"),
            q("D8",
              "Quarterly sales: Q1 = 400, Q2 = 500, Q3 = 550, Q4 = 450 (units). What is the ratio of Q2 to Q4 sales?",
              1, "MEDIUM", "Ratio from Table",
              "500 : 450 simplifies (÷50) to 10 : 9.",
              "11:9", "10:9", "9:10", "5:4"),
            q("D9",
              "A bar graph shows exports (million $): 2019 = 40, 2020 = 35, 2021 = 50, 2022 = 60. What is the total across all four years?",
              1, "EASY", "Bar Chart",
              "40 + 35 + 50 + 60 = 185 million $.",
              "190", "185", "175", "180"),
            q("D10",
              "In a class of 50, 30 passed Mathematics, 25 passed Physics, and 20 passed both. How many passed at least one subject?",
              0, "MEDIUM", "Set Theory",
              "At least one = 30 + 25 − 20 = 35.",
              "35", "30", "25", "40"));

    private static final Map<String, List<AptitudeTestDto.Question>> BANK = Map.of(
            "QUANTITATIVE", QUANTITATIVE,
            "LOGICAL", LOGICAL,
            "VERBAL", VERBAL,
            "PUZZLE", PUZZLE,
            "DI", DI);
}