package com.careeros.ai;

public enum AITask {
    RESUME_ANALYSIS,
    INTERVIEW_ASSISTANCE,
    CODING_ASSISTANCE,
    APTITUDE_GENERATION,
    PLACEMENT_READINESS,
    PLACEMENT_ROADMAP,
    GENERAL_CHAT
}
